GO
CREATE DATABASE QLBD

GO
USE QLBD

GO
CREATE TABLE ACCOUNT
(
	ACCOUNTID INT PRIMARY KEY,
	USERNAME VARCHAR(100) UNIQUE NOT NULL,
	DISPLAYNAME NVARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(1000) NOT NULL,
	ACCOUNTTYPE INT NOT NULL
)

GO
CREATE TABLE CLUB
(
	CLUBID INT PRIMARY KEY,
	CLUBSHORTNAME VARCHAR(6) UNIQUE NOT NULL,
	CLUBNAME NVARCHAR(100) NOT NULL,
	ESTABLISHEDYEAR INT NOT NULL,
	HOMEFIELD NVARCHAR(100) NOT NULL
)

GO
CREATE TABLE PLAYER
(
	PLAYERID INT PRIMARY KEY,
	CLUBID INT REFERENCES CLUB(CLUBID) ON DELETE CASCADE ON UPDATE CASCADE,
	NAME NVARCHAR(100) NOT NULL,
	NUMBER INT DEFAULT NULL,
	POSITION NVARCHAR(100) NOT NULL,
	NATIONALITY NVARCHAR(100) NOT NULL,
	BIRTHDAY DATETIME NOT NULL,
	AGE INT NOT NULL,
	HEIGHT INT NOT NULL,
	WEIGHT INT NOT NULL
)

GO
CREATE TABLE MATCH
(
	MATCHID INT PRIMARY KEY,
	HOMECLUB INT REFERENCES CLUB(CLUBID) NOT NULL,
	AWAYCLUB INT REFERENCES CLUB(CLUBID) NOT NULL,
	HOMESCORE INT NOT NULL,
	AWAYSCORE INT NOT NULL,
	ROUND INT NOT NULL,
	MATCHTIME DATETIME NOT NULL,
	ISPLAYED BIT DEFAULT 0
)

GO
CREATE TABLE GOALTYPE
(
	GOALTYPEID INT PRIMARY KEY,
	GOALTYPENAME NVARCHAR(100) NOT NULL
)

GO
CREATE TABLE GOAL
(
	GOALID INT PRIMARY KEY,
	MATCHID INT REFERENCES MATCH(MATCHID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	CLUBID INT REFERENCES CLUB(CLUBID) NOT NULL,
	PLAYERID INT REFERENCES PLAYER(PLAYERID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	GOALTYPEID INT REFERENCES GOALTYPE(GOALTYPEID) NOT NULL,
	GOALTIME INT NOT NULL,
	ISOWNGOAL BIT DEFAULT 0
)

GO
CREATE TABLE CARDTYPE
(
	CARDTYPEID INT PRIMARY KEY,
	CARDTYPENAME NVARCHAR(100) NOT NULL
)

GO
CREATE TABLE CARD
(
	CARDID INT PRIMARY KEY,
	MATCHID INT REFERENCES MATCH(MATCHID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	CLUBID INT REFERENCES CLUB(CLUBID) NOT NULL,
	PLAYERID INT REFERENCES PLAYER(PLAYERID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	CARDTYPEID INT REFERENCES CARDTYPE(CARDTYPEID) NOT NULL,
	CARDTIME INT NOT NULL,
)

GO
CREATE TABLE SETTING
(
	SETTINGKEY NVARCHAR(100) PRIMARY KEY,
	SETTINGVALUE NVARCHAR(100) NOT NULL
)


GO
CREATE TRIGGER TRG_INSTEAD_OF_DELETE_CLUB
ON CLUB
INSTEAD OF DELETE
AS
BEGIN
	DELETE FROM MATCH
	WHERE HOMECLUB IN (SELECT CLUBID
						FROM DELETED)

	DELETE FROM MATCH
	WHERE AWAYCLUB IN (SELECT CLUBID
						FROM DELETED)

	DELETE FROM GOAL
	WHERE CLUBID IN (SELECT CLUBID
						FROM DELETED)

	DELETE FROM CARD
	WHERE CLUBID IN (SELECT CLUBID
						FROM DELETED)

	DELETE FROM CLUB
	WHERE CLUBID IN (SELECT CLUBID
						FROM DELETED)
END


GO
CREATE TRIGGER TRG_INSERT_PLAYER
ON PLAYER
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @CLUBID INT,
			@NUMBER INT,
			@COUNT INT

	SELECT @CLUBID = I.CLUBID, @NUMBER = I.NUMBER
	FROM INSERTED AS I

	SELECT @COUNT = COUNT(*)
	FROM PLAYER AS P
	WHERE P.CLUBID = @CLUBID
	AND P.NUMBER = @NUMBER

	IF (@COUNT >= 2)
	BEGIN
		PRINT 'NUMBER MUST BE UNIQUE'
		ROLLBACK TRANSACTION
	END
END


GO
CREATE TRIGGER TRG_INSERT_GOAL
ON GOAL
FOR INSERT
AS
BEGIN
	DECLARE @MATCHID VARCHAR(6),
			@CLUBID INT
	
	SELECT @MATCHID = I.MATCHID, @CLUBID = I.CLUBID
	FROM INSERTED AS I

	UPDATE MATCH
	SET ISPLAYED = 1
	WHERE MATCHID = @MATCHID

	UPDATE MATCH
	SET HOMESCORE = HOMESCORE + 1
	WHERE HOMECLUB = @CLUBID
	AND MATCHID = @MATCHID

	UPDATE MATCH
	SET AWAYSCORE = AWAYSCORE + 1
	WHERE AWAYCLUB = @CLUBID
	AND MATCHID = @MATCHID

	DECLARE @GOALID INT,
			@CLUBOFPLAYER INT

	SELECT @GOALID = I.GOALID, @CLUBOFPLAYER = P.CLUBID
	FROM INSERTED AS I, PLAYER AS P
	WHERE I.PLAYERID = P.PLAYERID

	IF (@CLUBID <> @CLUBOFPLAYER)
	BEGIN
		UPDATE GOAL
		SET ISOWNGOAL = 1
		WHERE GOALID = @GOALID
	END
END


GO
CREATE TRIGGER TRG_DELETE_GOAL
ON GOAL
FOR DELETE
AS
BEGIN
	DECLARE @MATCHID INT,
			@CLUBID INT
	
	SELECT @MATCHID = D.MATCHID, @CLUBID = D.CLUBID
	FROM DELETED AS D

	UPDATE MATCH
	SET HOMESCORE = HOMESCORE - 1
	WHERE HOMECLUB = @CLUBID
	AND MATCHID = @MATCHID

	UPDATE MATCH
	SET AWAYSCORE = AWAYSCORE - 1
	WHERE AWAYCLUB = @CLUBID
	AND MATCHID = @MATCHID
END


GO
CREATE TRIGGER TRG_UPDATE_GOAL
ON GOAL
FOR UPDATE
AS
BEGIN
	UPDATE MATCH
	SET HOMESCORE = HOMESCORE - 1
	WHERE HOMECLUB = (SELECT D.CLUBID
						FROM DELETED AS D)
	AND MATCHID = (SELECT D.MATCHID
					FROM DELETED AS D)

	UPDATE MATCH
	SET HOMESCORE = HOMESCORE + 1
	WHERE HOMECLUB = (SELECT I.CLUBID
						FROM INSERTED AS I)
	AND MATCHID = (SELECT D.MATCHID
					FROM DELETED AS D)

	UPDATE MATCH
	SET AWAYSCORE = AWAYSCORE - 1
	WHERE AWAYCLUB = (SELECT D.CLUBID
						FROM DELETED AS D)
	AND MATCHID = (SELECT D.MATCHID
					FROM DELETED AS D)

	UPDATE MATCH
	SET AWAYSCORE = AWAYSCORE + 1
	WHERE AWAYCLUB = (SELECT I.CLUBID
						FROM INSERTED AS I)
	AND MATCHID = (SELECT D.MATCHID
					FROM DELETED AS D)
END





